name: blaze-dcpython-201608
channels:
- defaults
- conda-forge
dependencies:
- python=3.5.2=0
- blaze=0.10.1=py35_0
- bokeh=0.12.1=py35_0
- postgresql=9.5.3=2
- cytoolz=0.8.0=py35_0
- ipython=5.0.0=py35_0
- jupyter_client=4.3.0=py35_0
- jupyter_core=4.1.0=py35_0
- mongodb=3.3.9=0
- notebook=4.2.1=py35_0
- psycopg2=2.6.1=py35_1
- pymongo=3.0.3=py35_0
- tornado=4.4.1=py35_0
- pip:
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.3
  - tables==3.2.3.1
